packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@commitlint/cli': ^19.5.0
  '@commitlint/types': ^19.5.0
  miniprogram-recycle-view: 0.1.5
  '@types/node': ^22.0.0
  sass-embedded: ^1.89.2
  vue: ^3.5.17
  '@vueuse/core': ^11.0.1
  unocss: ^66.2.3
  axios: ^1.8.2
  js-base64: ^3.7.7
  mathjs: ^13.0.3
  pinia: ^2.2.2
  screenfull: ^6.0.2
  zod: ^3.23.8
  vitest: ^3.0.8
  vite-svg-loader: ^5.1.0
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-devtools: ^7.6.3
  vite-plugin-stylelint: ^5.3.1
  vite-plugin-top-level-await: ^1.4.2
  unplugin-vue-inspector: ^2.1.3
  unplugin-vue-define-options: ^1.5.5
  unplugin-auto-import: ^19.1.1
  unplugin-vue-components: ^28.4.1
  vue-eslint-parser: ^9.4.3
  vue-tsc: 2.0.29
  terser: ^5.31.3
  type-fest: ^4.26.1
  npm-check-updates: ^17.1.11
  rollup-plugin-visualizer: ^5.12.0
  autoprefixer: ^10.4.19
  '@iconify/json': ^2.2.231
  ua-parser-js: 2.0.0
  '@dotenvx/dotenvx': ^1.26.2
  globals: ^15.8.0
catalogs:
  stylelint:
    stylelint: ^16.11.0
  dev-tools:
    prettier: ^3.4.1
    turbo: ^2.5.4
    eslint: ^9.15.0
    husky: ^9.1.7
    lint-staged: ^15.2.10
    '@changesets/cli': ^2.27.10
    '@changesets/git': ^3.0.2
    '@taplo/cli': ^0.7.0
    '@manypkg/get-packages': ^2.2.2
  test:
    '@vue/test-utils': ^2.4.6
    '@testing-library/vue': ^8.1.0
    '@pinia/testing': ^0.1.5
    '@playwright/test': ^1.49.1
    playwright-core: ^1.49.1
    jest: ^29.7.0
  sentry:
    '@sentry/vite-plugin': ^2.22.4
    '@sentry/vue': ^8.31.0
  typescript:
    typescript: ^5.8.2
  vite:
    vite: ^6.2.1
    '@vitejs/plugin-vue-jsx': ^4.0.0
    '@vitejs/plugin-vue': ^5.2.1
    '@vitejs/plugin-legacy': ^5.4.3
  marked:
    marked: ^15.0.7
  lodash-es:
    lodash-es: ^4.17.21
    '@types/lodash-es': ^4.17.12
  jsdom:
    jsdom: ^24.1.1
    '@types/jsdom': ^21.1.7
  happy-dom:
    happy-dom: ^14.12.3
  semver:
    semver: ^7.6.3
    '@types/semver': ^7.5.8
  validator:
    validator: ^13.12.0
    async-validator: ^4.2.5
  uuid:
    uuid: 10.0.0
    '@types/uuid': 10.0.0
  sortablejs:
    sortablejs: ^1.15.2
    '@types/sortablejs': ^1.15.2
  postcss:
    postcss: ^8.4.49
    postcss-preset-env: ^10.0.9
    postcss-normalize: ^13.0.1
    '@types/postcss-normalize': ^9.0.4
  eslint:
    eslint: ^9.15.0
    '@types/eslint': ^9.6.1
    '@antfu/eslint-config': ^3.8.0
    eslint-plugin-vue: ^9.27.0
    eslint-plugin-prettier: ^5.2.1
    eslint-plugin-unused-imports: ^4.1.3
    eslint-plugin-import: ^2.30.0
    eslint-plugin-format: ^0.1.2
    eslint-import-resolver-alias: ^1.1.2
    '@vue/eslint-config-typescript': ^13.0.0
    '@vue/eslint-config-prettier': ^9.0.0
    '@unocss/eslint-plugin': ^0.62.4
    '@typescript-eslint/eslint-plugin': ^8.0.0
    '@typescript-eslint/parser': ^8.0.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.4.1
  obsidian:
    obsidian: ^1.8.7
    obsidian-dataview: ^0.5.68
    obsidian-typings: ^4.99.0