name: Bug Report
description: File a bug report
labels: ['bug']
title: '[Bug]: <TITLE>'
body:
  - type: markdown
    attributes:
      value: '**Please make sure you are on the latest version.**'
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: What's happening and when does it happen?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What SHOULD happen?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: The more detail you provide, the easier it will be to narrow down and fix the bug
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which OS are you using?
      options:
        - Windows
        - Linux
        - macOS
        - iOS
        - Android
    validations:
      required: true
