name: Feature Request
description: Suggest a Feature
labels: ['enhancement']
title: '[Feature]: <TITLE>'
body:
  - type: markdown
    attributes:
      value: Before getting started, please check the [GitHub Issues](https://github.com/uphy/obsidian-reminder/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Aenhancement+) (open or closed) for similar issues.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Goal or desired outcome of this feature
      description: Before describing your requested feature, please describe more generally the problem, pain-point, or use case you'd like to solve for.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature
      description: Please describe the desired feature in as much detail as you are able.
  - type: textarea
    attributes:
      label: Screenshots, mockups, or videos
      description: |
        If applicable, add screenshots, mockups, or videos to help demonstrate your feature request.
