import fs from 'fs';
import path from 'path';
import { SourceMapConsumer } from 'source-map';

// Path to file that is generated by your build tool (webpack, tsc, ...)
const sourceMapFile = './apps/tea-shop-2b-fe/dist/static/PayMethodsManage-DRClHUug.js.map'
const GENERATED_FILE = path.join(".", sourceMapFile);

// Line and column located in your generated file (for example, the source
// of the error from your minified file)
const GENERATED_LINE_AND_COLUMN = { line: 1, column: 1000 };

const rawSourceMap = fs.readFileSync(GENERATED_FILE).toString();

new SourceMapConsumer(rawSourceMap).then(smc => {
  const pos = smc.originalPositionFor(GENERATED_LINE_AND_COLUMN);

  // You should see something like:
  // { source: 'original.js', line: 57, column: 9, name: 'myfunc' }
  console.log(pos);
});
